// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb_vDu70tC0t39p05TIrt6BG0yt7-Y3ss',
    appId: '1:872003906528:web:2412317e7fd3bade4d9985',
    messagingSenderId: '872003906528',
    projectId: 'dclic-heath',
    authDomain: 'dclic-heath.firebaseapp.com',
    storageBucket: 'dclic-heath.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLt0bFqpjUTDrjM-EPUhRXDCLAJVWUm00',
    appId: '1:872003906528:android:2c0399b43df5a50f4d9985',
    messagingSenderId: '872003906528',
    projectId: 'dclic-heath',
    storageBucket: 'dclic-heath.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn5BwWatoVh2eJ0-TB1f2pgs7cIZkFFKg',
    appId: '1:872003906528:ios:7373dd1b3692f1a64d9985',
    messagingSenderId: '872003906528',
    projectId: 'dclic-heath',
    storageBucket: 'dclic-heath.firebasestorage.app',
    iosClientId: '872003906528-3h1q0ogo03jdi1omgfnka71h6mqe7g85.apps.googleusercontent.com',
    iosBundleId: 'com.example.mediclic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn5BwWatoVh2eJ0-TB1f2pgs7cIZkFFKg',
    appId: '1:872003906528:ios:7373dd1b3692f1a64d9985',
    messagingSenderId: '872003906528',
    projectId: 'dclic-heath',
    storageBucket: 'dclic-heath.firebasestorage.app',
    iosClientId: '872003906528-3h1q0ogo03jdi1omgfnka71h6mqe7g85.apps.googleusercontent.com',
    iosBundleId: 'com.example.mediclic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCb_vDu70tC0t39p05TIrt6BG0yt7-Y3ss',
    appId: '1:872003906528:web:37c0019d428144da4d9985',
    messagingSenderId: '872003906528',
    projectId: 'dclic-heath',
    authDomain: 'dclic-heath.firebaseapp.com',
    storageBucket: 'dclic-heath.firebasestorage.app',
  );

}